#!/usr/bin/env bash
# sim/pex/access-time/dut/generate.sh -- issue #95. Mechanically derives a
# klt-pex-compatible, .SUBCKT-wrapped copy of design/netlist/bitcell_6t.spice's
# own device cards.
#
# Why this exists (and why it isn't just design/netlist/bitcell_6t.spice
# itself): that file's own `.subckt`/`.ends` wrapper is commented out by
# xschem's netlister (it was netlisted as a standalone top-level schematic --
# see sim/README.md "Why two of the testbenches don't `.include` the DUT"),
# which is exactly what the ratified #24 write-margin/access-time
# testbenches need (Q/QB exposed as flat top-level nets via a plain
# `.include`). `klt pex`'s DUT-`.include`-swap convention instead needs a
# schematic-side `.SUBCKT` whose interface matches `klt extract`'s own
# output byte-for-byte (docs/cli/pex.md "The DUT .include swap") --
# `sim/pex/extracted-netlist/sram_bitcell_6t.spice` declares
# `.SUBCKT sram_bitcell_6t BL BLB Q QB VDD VSS WL` (7 pins -- Q/QB promoted
# to top-level pins by extraction, unlike the schematic file's own commented
# 5-pin header). This script wraps the SAME six device cards from
# bitcell_6t.spice (never hand-copied, never edited -- extracted
# mechanically below) in that exact interface, so a klt-pex-native
# testbench can `.include` this file on the schematic side and klt
# extract's own output unmodified on the extracted side, with a
# byte-identical `X`-instantiation on both legs.
#
# design/netlist/bitcell_6t.spice itself is NEVER modified by this script or
# committed to by this issue -- this file is a new, parallel artifact next
# to it, per issue #95's guardrails.
#
# Run from the repo root:
#     ./sim/pex/access-time/dut/generate.sh
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../../.." && pwd)"
SRC="$ROOT/design/netlist/bitcell_6t.spice"
OUT="$ROOT/sim/pex/access-time/dut/bitcell_6t_subckt.spice"

if [[ ! -f "$SRC" ]]; then
  echo "generate.sh: source netlist not found: $SRC" >&2
  exit 1
fi

SRC_SHA="$(sha256sum "$SRC" | cut -d' ' -f1)"

{
  echo "* AUTO-GENERATED by sim/pex/access-time/dut/generate.sh -- DO NOT EDIT BY HAND."
  echo "* issue #95 -- a klt-pex-compatible .SUBCKT wrapper around"
  echo "* design/netlist/bitcell_6t.spice's own six device cards, mechanically"
  echo "* extracted (never hand-transcribed) from that file below. See this"
  echo "* script's own header comment for why this wrapper is needed and"
  echo "* sim/pex/README.md for how it is used."
  echo "*"
  echo "* Source: design/netlist/bitcell_6t.spice"
  echo "* Source sha256: $SRC_SHA"
  echo "* Pin interface matches sim/pex/extracted-netlist/sram_bitcell_6t.spice's"
  echo "* own '.SUBCKT sram_bitcell_6t BL BLB Q QB VDD VSS WL' declaration"
  echo "* exactly (7 pins, same order) -- required for klt pex's DUT-.include"
  echo "* swap: the testbench's own X-instantiation line is reused"
  echo "* byte-identical on both the schematic and extracted legs."
  echo ".SUBCKT sram_bitcell_6t BL BLB Q QB VDD VSS WL"
  grep -v -E '^\*|^\.end[[:space:]]*$|^[[:space:]]*$' "$SRC"
  echo ".ENDS sram_bitcell_6t"
} >"$OUT"

echo "Wrote $OUT (from $SRC, sha256 $SRC_SHA)"
