#!/usr/bin/env python3
"""Render an explicit per-corner, per-metric PASS/FAIL signoff table.

Closes the one remaining gap the 2026-08-17 curator pass on issue #25
identified against the five append-only evidence records `run_corner_sweep.sh`
already produced under `sim/*/records/` (read SNM, hold SNM, write margin,
read access time, write access time -- all covering the ratified
process x temperature x voltage PVT matrix, `spec/sram.md` "Corner set",
27 distinct corner points): those records list raw measured values plus a
single aggregate `Overall: recorded` line, not an explicit per-corner
PASS/FAIL verdict against `spec/sram.md`'s Signoff definition.

This script does not re-run any simulation and does not modify any
committed record (`sim/`'s append-only rule, `sim/README.md` "Append-only
rule", stays intact). It only *derives* a rollup from records that are
already committed evidence, so it is safe to re-run at any time --
including after a future corner sweep supersedes one of today's records --
and its output should be regenerated (not hand-edited) whenever that
happens.

Verdict rule, per `spec/sram.md`'s Signoff definition ("### Signoff
definition"):
  - read SNM, hold SNM: PASS iff the recorded value is strictly > 0 V.
  - write margin (VDD - WTV, computed from the write-margin record's two
    RESULT lines per corner): PASS iff strictly > 0 V.
  - read/write access time: the spec only requires these be *recorded*
    (feeding Liberty views later), not compared against a numeric
    threshold -- so every corner with a valid measured value is marked
    RECORDED, not PASS/FAIL. A corner with no valid RESULT line (an
    OPEN result, see sim/README.md) is marked OPEN for any metric.

Usage:
    python3 sim/lib/render_signoff_table.py [repo-root]

Output: a Markdown document on stdout. The repo wraps this in
`sim/signoff-summary.md`, regenerated by re-running this script and
re-committing its output whenever any of the five source records is
superseded by a fresh sweep.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

# Ratified PVT matrix, spec/sram.md "Corner set" -- process x temperature x
# voltage, 3x3x3 = 27 points. Same order sim/lib/run_corner_sweep.sh
# iterates so every record's corner ordering already matches this.
PROCESSES = ["ff", "tt", "ss"]
TEMPS = ["-40", "25", "125"]
VDDS = ["2.97", "3.30", "3.63"]
CORNER_ORDER = [
    f"{p}_{t}c_{v}v" for p in PROCESSES for t in TEMPS for v in VDDS
]

RESULT_RE = re.compile(r"RESULT:\s*(\w+)\s*=\s*([-+0-9.eE]+)\s*;?")
ROW_RE = re.compile(r"^\s*-\s*\*\*(\S+)\*\*:\s*(.*)$")


def latest_record_for_claim(records_dir: Path, claim_substring: str) -> Path:
    """Return the most recent record file (by <record-id> filename, which
    sorts chronologically -- see sim/README.md's <record-id> convention)
    under records_dir whose Claim line contains claim_substring."""
    candidates = []
    for path in sorted(records_dir.glob("*.md")):
        text = path.read_text()
        for line in text.splitlines():
            if line.startswith("- **Claim**:") and claim_substring in line:
                candidates.append(path)
                break
    if not candidates:
        raise SystemExit(
            f"no record under {records_dir} has a Claim containing "
            f"{claim_substring!r}"
        )
    # <record-id> = <YYYYMMDD>-<HHMMSS>-<short-sha> sorts chronologically as
    # a plain string; take the lexicographically-last (= most recent).
    return sorted(candidates)[-1]


def parse_record(path: Path) -> dict[str, dict[str, float] | str]:
    """Parse a record's per-corner Result rows into
    {corner_id: {key: value, ...}} or {corner_id: "OPEN"} for an open
    result."""
    per_corner: dict[str, dict[str, float] | str] = {}
    for line in path.read_text().splitlines():
        m = ROW_RE.match(line)
        if not m:
            continue
        corner_id, rest = m.group(1), m.group(2)
        if corner_id.startswith("Overall"):
            continue
        if rest.startswith("OPEN"):
            per_corner[corner_id] = "OPEN"
            continue
        values = {k: float(v) for k, v in RESULT_RE.findall(rest)}
        if values:
            per_corner[corner_id] = values
    return per_corner


def fmt_v(x: float) -> str:
    return f"{x:.6f}"


def fmt_s(x: float) -> str:
    return f"{x:.4e}"


def verdict_threshold(value: float | None) -> str:
    if value is None:
        return "OPEN"
    return "PASS" if value > 0 else "FAIL"


def verdict_recorded(value: float | None) -> str:
    if value is None:
        return "OPEN"
    return "RECORDED"


def main() -> int:
    repo_root = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(__file__).resolve().parents[2]
    sim_dir = repo_root / "sim"

    read_snm_record = latest_record_for_claim(sim_dir / "read-snm" / "records", "read SNM")
    hold_snm_record = latest_record_for_claim(sim_dir / "hold-snm" / "records", "hold SNM")
    write_margin_record = latest_record_for_claim(sim_dir / "write-margin" / "records", "write margin")
    read_at_record = latest_record_for_claim(sim_dir / "access-time" / "records", "read access time")
    write_at_record = latest_record_for_claim(sim_dir / "access-time" / "records", "write access time")

    read_snm = parse_record(read_snm_record)
    hold_snm = parse_record(hold_snm_record)
    write_margin = parse_record(write_margin_record)
    read_at = parse_record(read_at_record)
    write_at = parse_record(write_at_record)

    rows = []
    metric_pass_counts = {
        "read_snm": [0, 0],  # [pass, total]
        "hold_snm": [0, 0],
        "write_margin": [0, 0],
    }
    metric_recorded_counts = {
        "read_access_time": [0, 0],
        "write_access_time": [0, 0],
    }
    all_pass = True

    for corner in CORNER_ORDER:
        rs = read_snm.get(corner)
        hs = hold_snm.get(corner)
        wm = write_margin.get(corner)
        rat = read_at.get(corner)
        wat = write_at.get(corner)

        rs_v = rs.get("read_snm_v") if isinstance(rs, dict) else None
        hs_v = hs.get("hold_snm_v") if isinstance(hs, dict) else None
        if isinstance(wm, dict) and "write_vdd_v" in wm and "write_trip_voltage_v" in wm:
            wm_v: float | None = wm["write_vdd_v"] - wm["write_trip_voltage_v"]
        else:
            wm_v = None
        rat_v = rat.get("read_access_time_s") if isinstance(rat, dict) else None
        wat_v = wat.get("write_access_time_s") if isinstance(wat, dict) else None

        rs_verdict = verdict_threshold(rs_v)
        hs_verdict = verdict_threshold(hs_v)
        wm_verdict = verdict_threshold(wm_v)
        rat_verdict = verdict_recorded(rat_v)
        wat_verdict = verdict_recorded(wat_v)

        metric_pass_counts["read_snm"][1] += 1
        metric_pass_counts["hold_snm"][1] += 1
        metric_pass_counts["write_margin"][1] += 1
        metric_recorded_counts["read_access_time"][1] += 1
        metric_recorded_counts["write_access_time"][1] += 1
        if rs_verdict == "PASS":
            metric_pass_counts["read_snm"][0] += 1
        if hs_verdict == "PASS":
            metric_pass_counts["hold_snm"][0] += 1
        if wm_verdict == "PASS":
            metric_pass_counts["write_margin"][0] += 1
        if rat_verdict == "RECORDED":
            metric_recorded_counts["read_access_time"][0] += 1
        if wat_verdict == "RECORDED":
            metric_recorded_counts["write_access_time"][0] += 1

        if rs_verdict != "PASS" or hs_verdict != "PASS" or wm_verdict != "PASS":
            all_pass = False

        row_overall = "PASS" if rs_verdict == hs_verdict == wm_verdict == "PASS" else "FAIL"

        rows.append(
            {
                "corner": corner,
                "rs_v": rs_v,
                "rs_verdict": rs_verdict,
                "hs_v": hs_v,
                "hs_verdict": hs_verdict,
                "wm_v": wm_v,
                "wm_verdict": wm_verdict,
                "rat_v": rat_v,
                "rat_verdict": rat_verdict,
                "wat_v": wat_v,
                "wat_verdict": wat_verdict,
                "row_overall": row_overall,
            }
        )

    def rel(p: Path) -> str:
        return str(p.relative_to(repo_root))

    lines = []
    lines.append("# PVT signoff summary (derived, per-corner pass/fail)")
    lines.append("")
    lines.append(
        "Auto-generated by `sim/lib/render_signoff_table.py` -- do not hand-edit."
        " Regenerate with:"
    )
    lines.append("")
    lines.append(
        "```bash\npython3 sim/lib/render_signoff_table.py > sim/signoff-summary.md\n```"
    )
    lines.append("")
    lines.append(
        "This document derives an explicit **per-corner, per-metric PASS/FAIL"
        " verdict** from the five append-only evidence records already"
        " committed under `sim/*/records/` (see `sim/README.md` for the"
        " record format and the append-only convention). It does not run any"
        " simulation and does not modify those records -- it is a read-only"
        " rollup, closing the one gap the 2026-08-17 curation pass on issue"
        " #25 identified: the source records report raw measured values plus"
        " a single aggregate `Overall: recorded` line, not a per-corner"
        " verdict against `spec/sram.md`'s Signoff definition."
    )
    lines.append("")
    lines.append("## Source records")
    lines.append("")
    lines.append(f"- Read SNM: `{rel(read_snm_record)}`")
    lines.append(f"- Hold SNM: `{rel(hold_snm_record)}`")
    lines.append(f"- Write margin: `{rel(write_margin_record)}` (margin computed as `write_vdd_v - write_trip_voltage_v`)")
    lines.append(f"- Read access time: `{rel(read_at_record)}`")
    lines.append(f"- Write access time: `{rel(write_at_record)}`")
    lines.append("")
    lines.append(
        "## Verdict rule (`spec/sram.md`, \"### Signoff definition\")"
    )
    lines.append("")
    lines.append(
        "- Read SNM, hold SNM, write margin: **PASS** iff the recorded value"
        " is strictly `> 0` V; **FAIL** otherwise; **OPEN** if the source"
        " record has no valid measurement for that corner (see"
        " `sim/README.md` \"Append-only rule\")."
    )
    lines.append(
        "- Read/write access time: `spec/sram.md` only requires these be"
        " **recorded**, not compared against a numeric threshold, so a"
        " corner with a valid measured value is marked **RECORDED**, not"
        " PASS/FAIL."
    )
    lines.append("")
    lines.append(
        f"**Note on corner count**: the table below has {len(CORNER_ORDER)}"
        " rows, one per distinct `process x temperature x voltage`"
        " combination actually swept by `sim/lib/run_corner_sweep.sh`"
        f" (`{len(PROCESSES)} x {len(TEMPS)} x {len(VDDS)} ="
        f" {len(CORNER_ORDER)}`), matching every one of the five source"
        " records above (each has exactly this many `- **<corner-id>**:`"
        " rows) and `spec/sram.md`'s \"Corner set\" section. That section"
        " computed the same product as \"9 corners\" until #53 corrected"
        " the arithmetic (3 x 3 x 3 = 27, not 9) -- see"
        " `spec/corner-count-correction.md`; the corner set, the Signoff"
        " definition, and every verdict below are unchanged by that"
        " correction. Records written before it still say \"9 corner"
        " points\" in their own generated prose while listing all 27 rows,"
        " because records are never edited after the fact"
        " (`sim/README.md`, \"Append-only rule\")."
    )
    lines.append("")
    lines.append("## Per-corner results")
    lines.append("")
    lines.append(
        "| Corner | Read SNM (V) | Verdict | Hold SNM (V) | Verdict |"
        " Write margin (V) | Verdict | Read access time (s) | Verdict |"
        " Write access time (s) | Verdict | Row overall (SNM + margin) |"
    )
    lines.append("|---|---|---|---|---|---|---|---|---|---|---|---|")
    for r in rows:
        lines.append(
            "| {corner} | {rs_v} | {rs_verdict} | {hs_v} | {hs_verdict} |"
            " {wm_v} | {wm_verdict} | {rat_v} | {rat_verdict} | {wat_v} |"
            " {wat_verdict} | {row_overall} |".format(
                corner=r["corner"],
                rs_v=fmt_v(r["rs_v"]) if r["rs_v"] is not None else "--",
                rs_verdict=r["rs_verdict"],
                hs_v=fmt_v(r["hs_v"]) if r["hs_v"] is not None else "--",
                hs_verdict=r["hs_verdict"],
                wm_v=fmt_v(r["wm_v"]) if r["wm_v"] is not None else "--",
                wm_verdict=r["wm_verdict"],
                rat_v=fmt_s(r["rat_v"]) if r["rat_v"] is not None else "--",
                rat_verdict=r["rat_verdict"],
                wat_v=fmt_s(r["wat_v"]) if r["wat_v"] is not None else "--",
                wat_verdict=r["wat_verdict"],
                row_overall=r["row_overall"],
            )
        )
    lines.append("")
    lines.append("## Aggregate")
    lines.append("")
    rs_pass, rs_total = metric_pass_counts["read_snm"]
    hs_pass, hs_total = metric_pass_counts["hold_snm"]
    wm_pass, wm_total = metric_pass_counts["write_margin"]
    rat_rec, rat_total = metric_recorded_counts["read_access_time"]
    wat_rec, wat_total = metric_recorded_counts["write_access_time"]
    min_rs = min((r["rs_v"] for r in rows if r["rs_v"] is not None), default=None)
    min_hs = min((r["hs_v"] for r in rows if r["hs_v"] is not None), default=None)
    min_wm = min((r["wm_v"] for r in rows if r["wm_v"] is not None), default=None)
    lines.append(f"- Read SNM: {rs_pass}/{rs_total} PASS (min {fmt_v(min_rs) if min_rs is not None else 'n/a'} V)")
    lines.append(f"- Hold SNM: {hs_pass}/{hs_total} PASS (min {fmt_v(min_hs) if min_hs is not None else 'n/a'} V)")
    lines.append(f"- Write margin: {wm_pass}/{wm_total} PASS (min {fmt_v(min_wm) if min_wm is not None else 'n/a'} V)")
    lines.append(f"- Read access time: {rat_rec}/{rat_total} RECORDED")
    lines.append(f"- Write access time: {wat_rec}/{wat_total} RECORDED")
    lines.append("")
    overall = "PASS" if all_pass else "FAIL"
    lines.append(
        f"**Overall signoff (read SNM + hold SNM + write margin, all"
        f" {len(CORNER_ORDER)} corner points, per `spec/sram.md`'s Signoff"
        f" definition): {overall}.**"
    )
    lines.append("")
    lines.append(
        "Footnote on write-margin resolution: issue #47 (WTV recorded at the"
        " first *failing* sweep step rather than the last *succeeding* one)"
        " was fixed in #54 and closed; the write-margin record cited above is"
        " a post-fix re-run, so that off-by-one does not apply to any number"
        " in this table. What remains is the search's inherent resolution:"
        " `tb_write_margin.spice` sweeps the trip voltage on a `VDD/40` grid"
        " (~0.074 V at 2.97 V, ~0.091 V at 3.63 V), so the true trip point"
        " lies within one step above each recorded WTV and every write margin"
        " above is optimistic by at most one step. That bound is ~17x smaller"
        " than the smallest margin in the table, so no corner's PASS verdict"
        " turns on it."
    )
    lines.append("")

    sys.stdout.write("\n".join(lines) + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
