#!/usr/bin/env python3
"""Generate design/sram_256x32_array.sch -- the 256 x 32 bitcell-array
schematic -- by tiling design/bitcell_6t.sym (issue #21, T1 item 1).

This is a *schematic-source generator*, analogous in spirit to
layout/bitcell/generate.py and layout/sram_256x32/generate.py (issue #22,
PR #36), which draw the GDS array programmatically via the klayout.db API
rather than by hand-placing 8,192 cells in a GUI. xschem's own .sch format
is plain text (documented informally by the xschem manual's "file format"
appendix; reverse-engineered here directly from files xschem itself wrote,
e.g. design/bitcell_6t.sch and gf180-bandgap's design/*.sch), so the same
"write the file directly, then let the real tool netlist it" pattern
applies here too: this script's only job is to emit valid xschem schematic
text; **xschem itself, not this script, is what turns it into a netlist**
(see design/README.md's regeneration recipe) -- the mechanical-derivation
requirement in issue #21's acceptance criteria is about the .sch -> .spice
step, which this script does not touch.

Connectivity technique: xschem merges nets purely by matching "lab="
text on lab_pin.sym / iopin.sym / ipin.sym instances -- no literal wire
routing is needed between instances that share a label (this is the same
technique gf180-bandgap's design/*.sch schematics use throughout, e.g.
every pfet_03v3 instance's bulk pin there is tied to "vdd" via a short stub
wire to a same-labelled lab_pin, not a routed rail). Each bitcell instance
gets five such stubs:
  - WL<row>   -- shared by all 32 cells in that row (wordline)
  - BL<col>, BLB<col> -- shared by all 256 cells in that column (bitline
    pair)
  - VDD, VSS  -- shared by all 8,192 cells (global rails)

Usage:
    python3 design/generate_array.py [--rows 256] [--cols 32] \\
        [--out design/sram_256x32_array.sch]

The committed array is the ratified fixed 256 x 32 instance (spec/sram.md);
--rows/--cols exist so the technique can be smoke-tested at a smaller scale
(see design/README.md), not because this repo's target is a generator.
"""
from __future__ import annotations

import argparse
import sys

# bitcell_6t.sym pin centers, relative to a cell placed at (ox, oy) with
# rot=0 flip=0 (see design/bitcell_6t.sym's B lines):
#   BL  ~ (ox-40, oy+40)     BLB ~ (ox-40, oy)      WL ~ (ox-40, oy-40)
#   VDD ~ (ox+40, oy+40)     VSS ~ (ox+40, oy-40)
# Stub wires extend 20 further outward in x before the label, matching the
# convention design/bitcell_6t.sch itself and gf180-bandgap's schematics use
# for device-pin-to-label stubs.
PIN_OFFSETS = {
    "BL": (-40, 40, -60, 40),
    "BLB": (-40, 0, -60, 0),
    "WL": (-40, -40, -60, -40),
    "VDD": (40, 40, 60, 40),
    "VSS": (40, -40, 60, -40),
}

X_PITCH = 200
Y_PITCH = 200


def emit_header(rows: int, cols: int) -> str:
    return f"""v {{xschem version=3.4.7 file_version=1.2
* sram_256x32_array -- {rows} x {cols} 6T bitcell array core (issue #21, T1
* item 1), MACHINE-GENERATED by design/generate_array.py -- do not
* hand-edit; re-run the generator instead (see design/README.md). Output is
* a pure function of --rows/--cols (no wall-clock/environment-dependent
* content), so re-running the generator reproduces this file byte-for-byte;
* provenance (who/when) belongs to git history, not the file body.
*
* Tiles design/bitcell_6t.sym {rows} x {cols} = {rows * cols} times. Net
* connectivity is established purely by matching "lab=" text (xschem's
* label-net convention -- see this script's module docstring), not by
* routed wires between cells:
*   WL0..WL{rows - 1}   -- one wordline per row, shared by all {cols} cells in
*                    that row
*   BL0..BL{cols - 1}, BLB0..BLB{cols - 1} -- one differential bitline pair per
*                    column, shared by all {rows} cells in that column
*   VDD, VSS  -- global rails, shared by all {rows * cols} cells
*
* This is the bitcell-array *core* only (spec/sram.md's ratified 256 x 32,
* single fixed instance) -- address decode, column mux, sense amp and
* write driver (the periphery needed to expose spec/sram.md's full 1RW
* macro pin list: A, CEN, CLK, D, Q, GWEN, WEN) are out of this issue's
* scope; the top-level ports below are the raw per-row/per-column array
* pins, matching layout/README.md's equivalent scoping note for the
* parallel GDS tiling (issue #22 / PR #36).
}}
G {{}}
K {{}}
V {{}}
S {{}}
E {{}}
"""


def emit_symbol_footer(rows: int, cols: int) -> str:
    lines = []
    name_id = 1

    def next_name(prefix: str) -> str:
        nonlocal name_id
        n = f"{prefix}{name_id}"
        name_id += 1
        return n

    lines.append("* --- top-level ports ---")
    for r in range(rows):
        lines.append(
            f"C {{ipin.sym}} -300 {r * Y_PITCH} 0 0 {{name={next_name('pwl')} lab=WL{r}}}"
        )
    for c in range(cols):
        x = c * X_PITCH
        lines.append(
            f"C {{iopin.sym}} {x} {rows * Y_PITCH + 100} 0 0 "
            f"{{name={next_name('pbl')} lab=BL{c}}}"
        )
        lines.append(
            f"C {{iopin.sym}} {x} {rows * Y_PITCH + 200} 0 0 "
            f"{{name={next_name('pblb')} lab=BLB{c}}}"
        )
    lines.append(
        f"C {{iopin.sym}} -300 {rows * Y_PITCH + 300} 0 0 {{name={next_name('pvdd')} lab=VDD}}"
    )
    lines.append(
        f"C {{iopin.sym}} -300 {rows * Y_PITCH + 400} 0 0 {{name={next_name('pvss')} lab=VSS}}"
    )
    return "\n".join(lines) + "\n"


def emit_array(rows: int, cols: int) -> str:
    out = []
    name_id = 1

    def next_name() -> str:
        nonlocal name_id
        n = f"l{name_id}"
        name_id += 1
        return n

    for r in range(rows):
        for c in range(cols):
            ox = c * X_PITCH
            oy = r * Y_PITCH
            out.append(
                f"C {{bitcell_6t.sym}} {ox} {oy} 0 0 {{name=Xr{r}c{c}}}"
            )
            for pin, net in (
                ("BL", f"BL{c}"),
                ("BLB", f"BLB{c}"),
                ("WL", f"WL{r}"),
                ("VDD", "VDD"),
                ("VSS", "VSS"),
            ):
                dx, dy, ex, ey = PIN_OFFSETS[pin]
                out.append(f"N {ox + dx} {oy + dy} {ox + ex} {oy + ey} {{}}")
                out.append(
                    f"C {{lab_pin.sym}} {ox + ex} {oy + ey} 0 0 "
                    f"{{name={next_name()} lab={net}}}"
                )
    return "\n".join(out) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--rows", type=int, default=256)
    parser.add_argument("--cols", type=int, default=32)
    parser.add_argument(
        "--out", default="design/sram_256x32_array.sch",
        help="output .sch path (default: design/sram_256x32_array.sch)",
    )
    args = parser.parse_args(argv)

    text = (
        emit_header(args.rows, args.cols)
        + emit_array(args.rows, args.cols)
        + emit_symbol_footer(args.rows, args.cols)
    )
    with open(args.out, "w") as f:
        f.write(text)
    print(
        f"wrote {args.out}: {args.rows} x {args.cols} = "
        f"{args.rows * args.cols} bitcell_6t instances",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
